# Generated by Django 5.2.6 on 2025-10-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.IntegerField()),
                ('consumo_energetico', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Vencido', 'Vencido')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('numero_contrato', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateField()),
                ('consumo_energetico', models.CharField(max_length=45)),
                ('tipo_lectura', models.CharField(choices=[('Digital', 'Digital'), ('Analogica', 'Analógica')], default='Digital', max_length=45)),
                ('lectura_actual', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_medidor', models.CharField(max_length=45)),
                ('fecha_instalacion', models.DateField()),
                ('ubicacion', models.CharField(max_length=45)),
                ('estado_medidor', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Mantenimiento', 'Mantenimiento'), ('Dañado', 'Dañado')], default='Activo', max_length=45)),
                ('imagen_ubicacion', models.URLField(blank=True, help_text='URL de la imagen de ubicación del medidor', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_consumo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda_pendiente', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=45)),
                ('numero_referencia', models.CharField(max_length=45)),
                ('estado_pago', models.CharField(choices=[('Pagado', 'Pagado'), ('No pagado', 'No pagado')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vigencia', models.DateField()),
                ('precio', models.IntegerField()),
                ('tipo_tarifa', models.CharField(choices=[('Verano', 'Verano'), ('Invierno', 'Invierno')], default='Verano', max_length=45)),
                ('tipo_cliente', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], default='Residencial', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Eléctrico', 'Eléctrico'), ('Finanzas', 'Finanzas')], max_length=45)),
            ],
        ),
    ]
