# Generated by Django 5.2.6 on 2025-10-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente', models.IntegerField(db_column='cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('email', models.CharField(blank=True, db_column='email', max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='telefono', null=True)),
                ('numero_cliente', models.CharField(db_column='numero_cliente', max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('email', models.CharField(blank=True, db_column='email', max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=45, null=True)),
                ('rol', models.CharField(db_column='rol', max_length=45)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('identificato', models.IntegerField(db_column='Identificato', primary_key=True, serialize=False)),
                ('fecha_inicio', models.CharField(db_column='fecha_inicio', max_length=45)),
                ('fecha_fin', models.CharField(blank=True, db_column='fecha_fin', max_length=45, null=True)),
                ('estado', models.CharField(db_column='estado', max_length=45)),
                ('numero_contrato', models.IntegerField(db_column='numero_contrato')),
                ('cliente_id_cliente', models.ForeignKey(db_column='Cliente_idCliente', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='sistemaGestion.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id_medidor', models.IntegerField(db_column='idMedidor', primary_key=True, serialize=False)),
                ('numero_medidor', models.IntegerField(db_column='numero_medidor')),
                ('fecha_instalacion', models.CharField(blank=True, db_column='fecha_instalacion', max_length=45, null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='ubicacion', max_length=45, null=True)),
                ('estado_medidor', models.CharField(blank=True, db_column='estado_medidor', max_length=45, null=True)),
                ('contrato_id_contrato', models.ForeignKey(db_column='Contrato_idContrato', on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='sistemaGestion.contrato')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
                'db_table': 'Medidor',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id_lectura', models.IntegerField(db_column='idLectura', primary_key=True, serialize=False)),
                ('fecha_lectura', models.CharField(db_column='fecha_lectura', max_length=45)),
                ('consumo_energetico', models.CharField(blank=True, db_column='consumo_energetico', max_length=45, null=True)),
                ('tipo_lectura', models.CharField(blank=True, db_column='tipo_lectura', max_length=45, null=True)),
                ('lectura_actual', models.CharField(db_column='lectura_actual', max_length=45)),
                ('medidor_contrato_id_contrato', models.ForeignKey(db_column='Medidor_Contrato_idContrato', on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sistemaGestion.contrato')),
                ('medidor_id_medidor', models.ForeignKey(db_column='Medidor_idMedidor', on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sistemaGestion.medidor')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'db_table': 'Lectura',
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.IntegerField(db_column='idBoleta', primary_key=True, serialize=False)),
                ('fecha_emision', models.CharField(db_column='fecha_emision', max_length=45)),
                ('fecha_vencimiento', models.CharField(db_column='fecha_vencimiento', max_length=45)),
                ('monto_total', models.IntegerField(db_column='monto_total')),
                ('consumo_energetico', models.CharField(blank=True, db_column='consumo_energetico', max_length=45, null=True)),
                ('estado', models.CharField(db_column='estado', max_length=45)),
                ('lectura_medidor_contrato_id_contrato', models.ForeignKey(db_column='Lectura_Medidor_Contrato_idContrato', on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='sistemaGestion.contrato')),
                ('lectura_id_lectura', models.ForeignKey(db_column='Lectura_idLectura', on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='sistemaGestion.lectura')),
                ('lectura_medidor_id_medidor', models.ForeignKey(db_column='Lectura_Medidor_idMedidor', on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='sistemaGestion.medidor')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'db_table': 'Boleta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(db_column='idPago', primary_key=True, serialize=False)),
                ('fecha_pago', models.CharField(db_column='fecha_pago', max_length=45)),
                ('monto_pagado', models.CharField(db_column='monto_pagado', max_length=45)),
                ('metodo_pago', models.CharField(db_column='metodo_pago', max_length=45)),
                ('numero_referencia', models.IntegerField(db_column='numero_referencia')),
                ('estado_pago', models.CharField(db_column='estado_pago', max_length=45)),
                ('boleta_id_boleta', models.ForeignKey(db_column='Boleta_idBoleta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sistemaGestion.boleta')),
                ('boleta_lectura_id_lectura', models.ForeignKey(db_column='Boleta_Lectura_idLectura', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sistemaGestion.lectura')),
                ('boleta_lectura_medidor_contrato_id_contrato', models.ForeignKey(db_column='Boleta_Lectura_Medidor_Contrato_idContrato', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sistemaGestion.contrato')),
                ('boleta_lectura_medidor_id_medidor', models.ForeignKey(db_column='Boleta_Lectura_Medidor_idMedidor', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sistemaGestion.medidor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.IntegerField(db_column='idTarifa', primary_key=True, serialize=False)),
                ('tipo_tarifa', models.CharField(db_column='tipo_tarifa', max_length=45)),
                ('tipo_cliente', models.CharField(blank=True, db_column='tipo_cliente', max_length=45, null=True)),
                ('fecha_vigencia', models.CharField(db_column='fecha_vigencia', max_length=45)),
                ('precio', models.IntegerField(db_column='precio')),
                ('contrato_id_contrato', models.ForeignKey(db_column='Contrato_idContrato', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='sistemaGestion.contrato')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'Tarifa',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.IntegerField(db_column='IdNotification', primary_key=True, serialize=False)),
                ('tipo_notification', models.CharField(db_column='tipo_notification', max_length=45)),
                ('estado_notification', models.CharField(db_column='estado_notification', max_length=45)),
                ('fecha_generation', models.CharField(db_column='fecha_generation', max_length=45)),
                ('fecha_revision', models.CharField(blank=True, db_column='fecha_revision', max_length=45, null=True)),
                ('lectura_id_lectura', models.ForeignKey(blank=True, db_column='Lectura_idLectura', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sistemaGestion.lectura')),
                ('lectura_medidor_contrato_id_contrato', models.ForeignKey(blank=True, db_column='Lectura_Medidor_Contrato_idContrato', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sistemaGestion.contrato')),
                ('lectura_medidor_id_medidor', models.ForeignKey(blank=True, db_column='Lectura_Medidor_idMedidor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sistemaGestion.medidor')),
                ('pago_id_pago', models.ForeignKey(blank=True, db_column='Pago_idPago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sistemaGestion.pago')),
                ('usuario_id_usuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sistemaGestion.usuario')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notification',
            },
        ),
    ]
