# Generated by Django 5.2.6 on 2025-10-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0003_alter_boleta_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionlectura',
            name='registro_consumo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notificacionpago',
            name='deuda_pendiente',
            field=models.CharField(max_length=500),
        ),
    ]
