# Generated by Django 5.2.6 on 2025-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0004_alter_notificacionlectura_registro_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='imagen_fisica',
            field=models.URLField(blank=True, null=True),
        ),
    ]
