# Generated by Django 5.2.6 on 2025-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0005_medidor_imagen_fisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('No pagado completamente', 'No pagado completamente')], default='Pagado', max_length=45),
        ),
    ]
