# Generated by Django 5.2.6 on 2025-11-09 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0006_alter_pago_estado_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleta',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Boleta', 'verbose_name_plural': 'Boletas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='lectura',
            options={'ordering': ['-fecha_lectura'], 'verbose_name': 'Lectura', 'verbose_name_plural': 'Lecturas'},
        ),
        migrations.AlterModelOptions(
            name='medidor',
            options={'ordering': ['-fecha_instalacion'], 'verbose_name': 'Medidor', 'verbose_name_plural': 'Medidores'},
        ),
        migrations.AlterModelOptions(
            name='notificacionlectura',
            options={'ordering': ['-fecha_notificacion'], 'verbose_name': 'Notificación de Lectura', 'verbose_name_plural': 'Notificaciones de Lectura'},
        ),
        migrations.AlterModelOptions(
            name='notificacionpago',
            options={'ordering': ['-fecha_notificacion'], 'verbose_name': 'Notificación de Pago', 'verbose_name_plural': 'Notificaciones de Pago'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='tarifa',
            options={'ordering': ['-fecha_vigencia'], 'verbose_name': 'Tarifa', 'verbose_name_plural': 'Tarifas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='boleta',
            name='lectura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='sistemaGestion.lectura', verbose_name='Lectura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='sistemaGestion.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='medidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sistemaGestion.medidor', verbose_name='Medidor'),
        ),
        migrations.AddField(
            model_name='medidor',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='sistemaGestion.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='notificacionlectura',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacionlectura',
            name='lectura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='sistemaGestion.lectura', verbose_name='Lectura'),
        ),
        migrations.AddField(
            model_name='notificacionpago',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacionpago',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='sistemaGestion.pago', verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='boleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sistemaGestion.boleta', verbose_name='Boleta'),
        ),
        migrations.CreateModel(
            name='Tarifa_has_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa_contratos', to='sistemaGestion.contrato', verbose_name='Contrato')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_tarifas', to='sistemaGestion.tarifa', verbose_name='Tarifa')),
            ],
            options={
                'verbose_name': 'Tarifa por Contrato',
                'verbose_name_plural': 'Tarifas por Contrato',
                'unique_together': {('tarifa', 'contrato')},
            },
        ),
    ]
