# Generated by Django 5.2.6 on 2025-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0007_alter_boleta_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='boleta',
            name='recargo_mora',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='consumo_energetico',
            field=models.CharField(editable=False, max_length=45),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
