# Generated by Django 5.2.6 on 2025-11-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0008_boleta_monto_base_boleta_recargo_mora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='monto_base',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='recargo_mora',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='consumo_energetico',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='monto_total',
            field=models.PositiveIntegerField(),
        ),
    ]
