# Generated by Django 5.2.6 on 2025-11-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0009_remove_boleta_monto_base_remove_boleta_recargo_mora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionlectura',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacionpago',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
    ]
