# Generated by Django 5.2.6 on 2025-11-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0010_notificacionlectura_revisada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pagado Parcialmente', 'Pagado Parcialmente'), ('Pendiente', 'Pendiente')], default='Pendiente', editable=False, max_length=45),
        ),
    ]
