# Generated by Django 5.2.6 on 2025-11-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0011_alter_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pagado Parcialmente', 'Pagado Parcialmente'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=45),
        ),
    ]
